### ISSUE TITLE
Build error: No 'content' or 'order' specified in technotes\flexing\index.md

### ISSUE THREAD

**Issue by Fatalerr** [jandecaluwe/urubu#19]
Hi, 
I'm runing urubu in win7+python2.7.9+virtualenv. it report an error when I added some deep sub-directories. I can't figure out why it complain "No 'content' or 'order'" in the index.md file. could you please give me a hint on this problem? thanks a lot!

here is the build error msg:

````
(webdev) R:\infohub>python -m urubu build
Traceback (most recent call last):
  File "C:\WinPython\python-2.7.9.amd64\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\WinPython\python-2.7.9.amd64\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\jliut\Envs\webdev\lib\site-packages\urubu\__main__.py", line 20, in <module>
    main.main()
  File "C:\Users\jliut\Envs\webdev\lib\site-packages\urubu\main.py", line 48, in main
    project.build()
  File "C:\Users\jliut\Envs\webdev\lib\site-packages\urubu\project.py", line 457, in build
    proj.get_contentinfo()
  File "C:\Users\jliut\Envs\webdev\lib\site-packages\urubu\project.py", line 187, in get_contentinfo
    self.validate_navinfo(relfn, navinfo)
  File "C:\Users\jliut\Envs\webdev\lib\site-packages\urubu\project.py", line 233, in validate_navinfo
    raise UrubuError(undef_content_error.format(relfn))
urubu.UrubuError: No 'content' or 'order' specified in technotes\flexing\index.md
````

here is my directory structure.
````
project-dir
 |--_site.yaml
 |-- index.md
 |-- technotes
            |--flexing
                    |--index.md
````     
and the content of  'technotes\flexing\index.md':

````
---
title: FlexiNG Technical Notes
layout: page 
pager: true
---

First section
=============

Second Section
=============
````

**Comment by jandecaluwe** [comment]
http://urubu.jandecaluwe.com/manual/structure.html#index-files

**Comment by Fatalerr** [comment]
Thanks Jandecaluwe, It's shame on me that miss this part in the document. :(
