### ISSUE TITLE
Unable to have content files with non-lowercase filenames

### ISSUE THREAD

**Issue by skoenig** [jandecaluwe/urubu#23]
I stumbled upon this bug (or maybe its intended) when I tried to generate a project from a bunch of personel wiki-pages, which have title-case filenames like 'Static-HTML-Generators.md'.
Reproducable with:

    git clone https://github.com/jandecaluwe/urubu-quickstart.git
    cd urubu-quickstart
    mv organize.md Organize.md
    make

The error message is this:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/urubu/__main__.py", line 20, in <module>
    main.main()
  File "/usr/local/lib/python2.7/dist-packages/urubu/main.py", line 48, in main
    project.build()
  File "/usr/local/lib/python2.7/dist-packages/urubu/project.py", line 460, in build
    proj.make_breadcrumbs()
  File "/usr/local/lib/python2.7/dist-packages/urubu/project.py", line 356, in make_breadcrumbs
    breadcrumbs.append(self.site['reflinks'][id])
KeyError: u'/Organize'
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 1
```

So, the reflink id is assumed to be the filepath without extension here, while it is lowercased at another place in the code, thus resulting in an KeyError while looking it up.
I would sugget to make a clear distinction between the id anf the URL of an reflink while make it possible to have non-lowercased content files. A quick fix would look like this:
```
diff --git a/urubu/project.py b/urubu/project.py
index 2064747..512f5f4 100644
--- a/urubu/project.py
+++ b/urubu/project.py
@@ -71,6 +71,9 @@ def get_components(path, hasext=True):
     return components
 
 
+def make_url(components):
+    return ('/' + '/'.join(components))
+
 def make_id(components):
     return ('/' + '/'.join(components)).lower()
 
@@ -241,7 +244,7 @@ class Project(object):
         info['id'] = make_id(components)
         # make html url from ref
         info['url'] = self.finalize_local_url(
-            info['id'] + self.site['link_ext'])
+            make_url(components) + self.site['link_ext'])
         info.update(meta)
         return info
 
@@ -353,6 +356,7 @@ class Project(object):
                 comps = comps[:-1]
             for comp in comps:
                 id = id + '/' + comp
+                id = id.lower()
                 breadcrumbs.append(self.site['reflinks'][id])
             info['breadcrumbs'] = breadcrumbs
 ```
(Maybe introducing make_url() which is almost a complete duplicate of make_id() is not that elegant). Should I create a PR?

**Comment by jandecaluwe** [comment]
Suggestion: define make_id() using make_url() to avoid duplication. PR welcome.
