### ISSUE TITLE
Urubu running on Python 3.6.4

### ISSUE THREAD

**Issue by conradek** [jandecaluwe/urubu#75]
Searching appears to be broken when running Urubu 1.3.0 with Python 3.6.4.  When searching, no results are returned.  When testing with the latest Python 2.7, searching functions as expected.  I am testing with the Quickstart site.

Here is the exception when building:

(urubu_p364) urubu-quickstart-master>python -m urubu build
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cek/virtual_environments/urubu_p364/lib/python3.6/site-packages/urubu/__main__.py", line 20, in <module>
    main.main()
  File "/home/cek/virtual_environments/urubu_p364/lib/python3.6/site-packages/urubu/main.py", line 51, in main
    project.build()
  File "/home/cek/virtual_environments/urubu_p364/lib/python3.6/site-packages/urubu/project.py", line 489, in build
    proj.make_site()
  File "/home/cek/virtual_environments/urubu_p364/lib/python3.6/site-packages/urubu/project.py", line 470, in make_site
    self.process_content()
  File "/home/cek/virtual_environments/urubu_p364/lib/python3.6/site-packages/urubu/project.py", line 476, in process_content
    p.process()
  File "/home/cek/virtual_environments/urubu_p364/lib/python3.6/site-packages/urubu/processors.py", line 106, in process
    self.make_tipuesearch_content()
  File "/home/cek/virtual_environments/urubu_p364/lib/python3.6/site-packages/urubu/processors.py", line 205, in make_tipuesearch_content
    data = json.dumps(obj, fd, ensure_ascii=False, indent=4, sort_keys=True)
TypeError: dumps() takes 1 positional argument but 2 positional arguments (and 3 keyword-only arguments) were given

Any ideas here?

**Comment by conradek** [comment]
Thanks, that fixed the issue!  Any ideas on when the next release will be?

**Comment by conradek** [comment]
Great idea!
